function(tanh_rtsan_configure target)
    target_compile_definitions(${target} PUBLIC TANH_WITH_RTSAN)
    target_compile_options(${target} PUBLIC -fsanitize=realtime)
    target_link_options(${target} PUBLIC -fsanitize=realtime)
endfunction()