function(tanh_realtime_sanitizer target)
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        message(FATAL_ERROR "RTSan (-fsanitize=realtime) requires Clang. Current compiler: ${CMAKE_CXX_COMPILER_ID}")
    endif()
    target_compile_definitions(${target} PUBLIC TANH_WITH_RTSAN)
    target_compile_options(${target} PUBLIC -fsanitize=realtime)
    target_link_options(${target} PUBLIC -fsanitize=realtime)
endfunction()

function(tanh_address_sanitizer target)
    target_compile_definitions(${target} PUBLIC TANH_WITH_ASAN)
    target_compile_options(${target} PUBLIC -fsanitize=address)
    target_link_options(${target} PUBLIC -fsanitize=address)
    set(IGNORELIST "${CMAKE_SOURCE_DIR}/sanitizers/asan_ignorelist.txt")
    if(EXISTS "${IGNORELIST}")
        target_compile_options(${target} PUBLIC "-fsanitize-ignorelist=${IGNORELIST}")
    endif()
endfunction()

function(tanh_undefined_sanitizer target)
    target_compile_definitions(${target} PUBLIC TANH_WITH_USAN)
    target_compile_options(${target} PUBLIC -fsanitize=undefined)
    target_link_options(${target} PUBLIC -fsanitize=undefined)
endfunction()

function(tanh_thread_sanitizer target)
    target_compile_definitions(${target} PUBLIC TANH_WITH_TSAN)
    target_compile_options(${target} PUBLIC -fsanitize=thread)
    target_link_options(${target} PUBLIC -fsanitize=thread)
endfunction()

function(tanh_memory_sanitizer target)
    target_compile_definitions(${target} PUBLIC TANH_WITH_MSAN)
    target_compile_options(${target} PUBLIC -fsanitize=memory)
    target_link_options(${target} PUBLIC -fsanitize=memory)
endfunction()

function(tanh_leak_sanitizer target)
    target_compile_definitions(${target} PUBLIC TANH_WITH_LSAN)
    target_compile_options(${target} PUBLIC -fsanitize=leak)
    target_link_options(${target} PUBLIC -fsanitize=leak)
endfunction()
